[window]
padding.x = 7 
padding.y = 5 

decorations = "Buttonless"

opacity = 0.57
blur = true

option_as_alt = "Both"

[font]
size = 16

# Set the font family to Hack Nerd Font for icon rendering
normal.family = "JetBrainsMono Nerd Font"
normal.style = "Regular"

bold.family = "JetBrainsMono Nerd Font"
bold.style = "Bold"

italic.family = "JetBrainsMono Nerd Font"
italic.style = "Italic"

bold_italic.family = "JetBrainsMono Nerd Font"
bold_italic.style = "Bold Italic"

[window.dimensions]
columns = 120
lines = 80


[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]
